//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Alumno.java
//  @ Date : 9/3/2021
//  @ Author : 
//
//




public class Alumno {
	private int matricula;
	private int cantCreditos;
	public void Alumno() {
	
	}
	
	public String toString() {
	
	}
	
	public double calcularColegiatura() {
	
	}
}
