//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Alumno.java
//  @ Date : 9/3/2021
//  @ Author : 
//
//




import java.util.*;
import java.text.*;

public class Alumno {
	private int matricula;
	private int cantCreditos;
	public Alumno(int matricula, int cantCreditos) {
   setMatricula(matricula);
   setCantCreditos(cantCreditos);
	
	}
   public void setMatricula(int matricula){
      	this.matricula=matricula;
      }
    	public int getMatricula(){
      	return matricula;
      }
        public void setCantCreditos(int cantCreditos){
        this.cantCreditos=cantCreditos;
      }
        public int getCantCreditos(){
        return cantCreditos;
      }
      
	
	public String toString() {
   DecimalFormat d = new DecimalFormat("0.00");
		return "El costo de la colegiatura es de $"+d.format(calcularColegiatura());
	}
	
	public double calcularColegiatura() {
   double total = (cantCreditos * 2300);
   return total;
  
	
	}   
   }
   
   class Principal{
      public static void main(String arg[]){
         Scanner s = new Scanner(System.in);
         int matricula;
         do{
         	System.out.println("Escriba su matricula");
         	matricula = s.nextInt();
         }while(matricula<0);
         int cantCreditos;
         do{
         	System.out.println("Escriba la cantidad de creditos que cursara");
         	cantCreditos = s.nextInt();
         }while(cantCreditos<0);
         Alumno A1 = new Alumno(matricula, cantCreditos);
         System.out.println(A1);
      }
         
   }
