//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Articulo.java
//  @ Date : 8/30/2021
//  @ Author : Equipo alfa buena maravilla onda dinamita escuadrón lobo
//
//




public class Articulo {
	private String nombre;
	private double precio;
   
	public Articulo() {
	
	}
	
	public String toString() {
	
	}
	
	public double calcularNuevoPrecio() {
	
	}
}
