//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Articulo.java
//  @ Date : 8/30/2021
//  @ Author : Equipo alfa buena maravilla onda dinamita escuadrón lobo
//  Objetivo del programa: calcular el precio total de un artículo con impuesto, el cual varía según el costo básico del artículo
//


import java.text.*;
import java.util.*;

//Creamos el objeto Articulo, con nombre y precio como atributos para cambiar nuestro antiguo programa a un POO.

public class Articulo {
	private String nombre;
	private double precio;
   	
	//Método constructor
	public Articulo(String nombre, double precio) {
		this.nombre = nombre;
      		this.precio = precio;
	}
	
	//Método toString() para imprimir la respuesta
	public String toString() {
		DecimalFormat d = new DecimalFormat("0.00");
		return "El nuevo precio del artículo es: $"+d.format(calcularNuevoPrecio());
	}
	
	//Método matemático para calcular el nuevo precio dependiendo de que tan caro es.
	public double calcularNuevoPrecio() {
		if (precio>500)
         		precio = precio+6+(precio-40)*0.5;
     		else
         		if (precio>40)
            			precio = precio+6+(precio-40)*0.4;
         		else 
            			if (precio>20)
              				 precio = precio+(precio-20)*0.3;
      		return precio;

	}
}
class Principal {
	
	//Método main
	public static void main(String args[]) {
		String nombre = Principal.capturarNombre();
		double precio = Principal.capturarPrecio();
        	Articulo a1 = new Articulo(nombre,precio);
		System.out.println(a1);
   }
	//Método para capturar el costo del producto
   	public static double capturarPrecio() {
      		Scanner s = new Scanner(System.in);
      		System.out.println("Ingrese el costo basico del articulo: ");
      		double precio = s.nextDouble();
      		while (precio<0) {
         		System.out.println("Ingrese un numero positivo: ");
         		precio = s.nextDouble();
      		}
      		return precio;
	}
	
	//Método para ingresar el nombre del artículo comprado
	public static String capturarNombre() {
      		Scanner s = new Scanner(System.in);
      		System.out.println("Ingrese el nombre del articulo ");
      		String nombre = s.next();
      		return nombre;
   }

}




