//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mes.java
//  @ Date : 17/10/2021
//  @ Author : 
//
//
import java.io.*;
import java.util.*;
import java.text.*;

//clase mes
class Mes {
	
	private String nombre;
	private double temperatura;
	public Mes(String nombre, double temperatura) {
		setNombre(nombre);
		setTemperatura(temperatura);
	}
	//metodos set y get
	public void setNombre(String nombre) {
		this.nombre=nombre;
	}
	
	public void setTemperatura(double temperatura) {
		this.temperatura=temperatura;
	}
	public void setMes(Mes m[]){
		this.m=m;
	}
	
	public String getNombre() {
		return nombre;
	}
	
	public double getTemperatura() {
		return temperatura;
	}
	public Mes[] getMes(){
		return m;
	}
	public String toString(){
		return " "+getTemperatura();
	}
}
//clase principal
class Principal{
	public static void main (String agrs []){
		String meses[]={"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
		Mes m[]=new Mes[12];
		for (byte i=0;i<12;i++){
			m[i]=new Mes(meses[i],Principal.capturarTemperatura());
		}
		for (byte i=0;i<12;i++){
			System.out.println(meses[i]+m[i].getTemperatura());
		}
	}

	public static double capturarTemperatura(){
		Scanner s=new Scanner(System.in);
		System.out.println("Ingresa la temperatura");
		double temperatura=s.nextDouble();
		return temperatura;
	}
}
